name = "Nibe-MC-Server"
author = "Matuha04"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f82e245af820167de849c76e5d86788e33d145f8d4863526b51a12f2b133c444"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
