name = "Nibe-MC-Server"
author = "Matuha04"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d095b49adfd44cc804997ec807841e35ee2a86a80e86ba3c09067e91f464a04"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
